//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public int PersonID { get; set; }
        public int Channel { get; set; }
        public int FundRaiser { get; set; }
        public Nullable<int> Outcome { get; set; }
        public string Notes { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> DonationID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual LOV LOV_Channel { get; set; }
        public virtual LOV LOV_Fundraiser { get; set; }
        public virtual LOV LOV_Outcome { get; set; }
        private Person Person { get; set; }
    }
}
