//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int DonationID { get; set; }
        public int PersonID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DonationDate { get; set; }
        public int Source { get; set; }
    
        private ICollection<Contact> Contacts { get; set; }
        public virtual LOV LOV_Source { get; set; }
        private Person Person { get; set; }
    }
}
