//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public int InterestID { get; set; }
        public int PersonID { get; set; }
        public int Interest1 { get; set; }
    
        public virtual LOV LOV { get; set; }
        private Person Person { get; set; }
    }
}
