//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOVType
    {
        public LOVType()
        {
            this.LOVs = new HashSet<LOV>();
        }
    
        public int LOVTypeID { get; set; }
        public string LOVName { get; set; }
    
        public virtual ICollection<LOV> LOVs { get; set; }
    }
}
