//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Contacts = new HashSet<Contact>();
            this.Donations = new HashSet<Donation>();
            this.Interests = new HashSet<Interest>();
        }
    
        public int PersonID { get; set; }
        public int PersonType { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public int Gender { get; set; }
        public string OrgName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string EmailAddress { get; set; }
        public string Phone1 { get; set; }
        public Nullable<int> PhoneType1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> PhoneType2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<int> PhoneType3 { get; set; }
        public Nullable<int> ContactPreference { get; set; }
        public string FamilyInfo { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual LOV LOV_ContactPreference { get; set; }
        public virtual LOV LOV_Gender { get; set; }
        public virtual LOV LOV_PersonType { get; set; }
        public virtual LOV LOV_PhoneType1 { get; set; }
        public virtual LOV LOV_PhoneType2 { get; set; }
        public virtual LOV LOV_PhoneType3 { get; set; }
    }
}
